language: python
python:
  - "2.6"
  - "2.7"

env:
-DJANGO=1.6 DB=mysqlite

install:
  - pip install -e .

script:
  - python manage.py test

notifications:
  emails:
    recipients:
      - info@jozihub.org
    on_success: [always|never|change]
    on_failure: [always|never|change]
